# When updating, check https://github.com/numba/llvmlite/tree/master/conda-recipes/llvmdev and
# update patches as necessary.
{% set version = "14.0.6" %}

package:
  name: chaquopy-llvm
  version: {{ version }}

build:
  number: 2

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-{{ version }}.src.tar.xz
  #  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-{{ version }}.src.tar.xz
#  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version }}.tar.gz
#
#url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz

requirements:
  build:
    - cmake
