package:
  name: numpy
  version: 1.24.2

build:
  number: 0

requirements:
  build:
    - Cython 0.29.32
    - setuptools 63.0.0 # Issue with setuptools >= 64 cf https://github.com/pypa/setuptools/issues/3549
  host:
    - chaquopy-openblas 0.3.23
