package:
  name: openai-tiktoken
  version: 0.3.3

build:
  number: 0

source:
  git_url: https://github.com/openai/tiktoken.git
  git_rev: e1c661edf3604706bb2db59cfc7bf92f73c09761

requirements:
  host:
    - python
