package:
  name: chaquopy-openblas
  version: 0.3.23

source:
  url: https://github.com/xianyi/OpenBLAS/archive/refs/tags/v0.3.23.zip

build:
  number: 5

requirements:
  build:
    - fortran
  host:
    - chaquopy-libgfortran 4.9
